## Numpy Array Operations

### Slicing

In [5]:
import numpy as np


In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print("Basic Slicing: ", arr[2:7])
print("With Step: ",arr[1:8:2])
print("Negative Indexing: ",arr[-2])

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
print("Specefic Element: ", array_2d[1, 2])
print("Specefic Row: ", array_2d[1, :])
print("Specefic Element: ", array_2d[:, 2])

Basic Slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative Indexing:  9
Specefic Element:  6
Specefic Row:  [4 5 6]
Specefic Element:  [3 6]


### Sorting Arrays

In [7]:
unsorted_array = np.array([1,4, 3, 6, 5, 2, 8, 9, 7, 8])
unsorted_2d_array = np.array([[1, 2, 4],
                              [1, 4, 2]])

print("Sorted Array: ", np.sort(unsorted_array))
print("Sorted 2D array by column: \n", np.sort(unsorted_2d_array, axis=0))
print("Sorted 2D array by row: \n", np.sort(unsorted_2d_array, axis=1))



Sorted Array:  [1 2 3 4 5 6 7 8 8 9]
Sorted 2D array by column: 
 [[1 2 2]
 [1 4 4]]
Sorted 2D array by row: 
 [[1 2 4]
 [1 2 4]]


### Filters and mask

In [8]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
conditioned = numbers[numbers % 2 == 0]
print("Even Numbers: ", conditioned)

mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Even Numbers:  [ 2  4  6  8 10]
Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [9]:
indices = [0 ,2, 4]
print(numbers[indices])

result = np.where(numbers > 5)
print(result)
print("Here ", numbers[result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Here  [ 6  7  8  9 10]


In [10]:
condition_arrays = np.where( numbers > 5, numbers*2, numbers)
condition_array = np.where( numbers < 50, numbers*2, numbers)
#                  if-else    condition      if       else
print(condition_arrays, condition_array)

[ 1  2  3  4  5 12 14 16 18 20] [ 2  4  6  8 10 12 14 16 18 20]


In [11]:
one = np.array([1, 2, 3, 4])
two = np.array([5, 6, 7, 8])
combined = np.concatenate((one, two))
print("Combined: ", combined)
new_row = np.array([1, 8, 3, 5])
new_col = np.array([4, 3])

print("Combined with row:\n", np.vstack((one, new_row)))
print("Combined with col:\n", np.hstack((one, new_col)))

Combined:  [1 2 3 4 5 6 7 8]
Combined with row:
 [[1 2 3 4]
 [1 8 3 5]]
Combined with col:
 [1 2 3 4 4 3]


In [16]:
aarr1 = np.array([[1, 2, 3, 4, 5],
                  [1, 2, 3, 4, 5],
                  [1, 2, 3, 4, 5]])
print(aarr1[1:,1:4])

[[2 3 4]
 [2 3 4]]


In [24]:
aray = np.arange(1,20,2)
arey = aray
print(arey)
arey[3:] = 100
print(arey)
print(aray)

[ 1  3  5  7  9 11 13 15 17 19]
[  1   3   5 100 100 100 100 100 100 100]
[  1   3   5 100 100 100 100 100 100 100]


In [23]:
aray = np.arange(1,20,2)
arey = aray.copy()
print(arey)
arey[3:] = 100
print(arey)
print(aray)

[ 1  3  5  7  9 11 13 15 17 19]
[  1   3   5 100 100 100 100 100 100 100]
[ 1  3  5  7  9 11 13 15 17 19]


In [29]:
aruy = np.arange(0,10).reshape(5,2)
print(aruy)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
