## Numy array and basics

In [1]:
import numpy as np
import time

In [2]:
array_1d = np.array([1,2,3])
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_1d, array_2d)

[1 2 3] [[1 2 3]
 [4 5 6]]


In [9]:
start = time.time()
mylist = [i*2 for i in range (1000000)]
print("\nList operation time: ", time.time()-start)

new = time.time()
myarray = np.arange(1000000) * 2
print("\nArray operation time: ", time.time()-new)


List operation time:  0.14465594291687012

Array operation time:  0.0056722164154052734


## Creating Arrays from Scratch

In [12]:
zeros = np.zeros((3, 3))
print("Zeros Array is:\n", zeros)

ones = np.ones((3, 3))
print("Ones Array is:\n", ones)

fulls = np.full((3, 3), 7)
print("Fulls array is:\n", fulls)

randomness = np.random.random((2,3))
print("Random array is:\n", randomness)

sequenced = np.arange(1, 10, 2)
print("Sequenced array is:\n", sequenced)


Zeros Array is:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array is:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Fulls array is:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random array is:
 [[0.27871148 0.89279148 0.75069927]
 [0.6193095  0.70229753 0.16519404]]
Sequenced array is:
 [1 3 5 7 9]


## Vector, Matrix and Tensor

In [8]:
vector = np.array([1,2,3])
print(vector)

matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

tensor = np.array([[[1, 2], [4, 5]],
                   [[7, 8], [1, 2]]])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [4 5]]

 [[7 8]
  [1 2]]]


### Array and it's Properties


In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


### Array Reshaping

In [12]:
arr = np.arange(12)
print("Original: \n", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped: \n", reshaped)

flattened = reshaped.flatten()
print("Flattened: \n", flattened)

Transposed = reshaped.T
print("Transposed: \n", Transposed)

# ravel = ( return view, instead of copy)
raveled = flattened.ravel()
print("Ravel: \n", raveled)

Original: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Ravel: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
